import { getEvents, saveEvents, saveImage, imageUrl } from "./storage.js";
import { downloadBackup, restoreBackup } from "./backup.js";
import { renderCalendar, monthTitle } from "./calendar.js";
import { renderTimeline, rangeFor, iso } from "./timeline.js";
import { printTimeline } from "./timelinePrint.js";
const $ = s => document.querySelector(s); let events=[], library=[], current=new Date(), selectedStage=null, activeRange;
async function init() { library=await fetch("images/manifest.json").then(r=>r.json()); events=await getEvents(); bind(); refresh(); }
function bind() {
  document.querySelectorAll("[data-view]").forEach(btn=>btn.onclick=()=>{ document.querySelectorAll("[data-view],.view").forEach(x=>x.classList.remove("active")); btn.classList.add("active"); $(`#${btn.dataset.view}-view`).classList.add("active"); if(btn.dataset.view==="timeline") refreshTimeline(); });
  $("#prev-month").onclick=()=>{current.setMonth(current.getMonth()-1);refreshCalendar()}; $("#next-month").onclick=()=>{current.setMonth(current.getMonth()+1);refreshCalendar()}; $("#today-button").onclick=()=>{current=new Date();refreshCalendar()};
  $("#range-kind").onchange=refreshTimeline; $("#range-start").onchange=refreshTimeline; $("#range-end").onchange=refreshTimeline; $("#print-timeline").onclick=()=>printTimeline($("#timeline"),activeRange);
  $("#add-event").onclick=()=>openForm(); $("#add-stage").onclick=()=>addStage(); $("#event-form").onsubmit=saveForm;
  $("#export").onclick=()=>downloadBackup(events); $("#import").onchange=async e=>{if(!e.target.files[0])return; try{events=await restoreBackup(e.target.files[0]);refresh();alert("読み込みました。")}catch(err){alert(err.message)} e.target.value=""};
  $("#close-image").onclick=()=>$("#image-dialog").close(); $("#image-upload").onchange=uploadImage;
}
function refresh(){refreshCalendar(); refreshTimeline()}
function refreshCalendar(){ $("#month-title").textContent=monthTitle(current.getFullYear(),current.getMonth()); renderCalendar($("#calendar"),events,current.getFullYear(),current.getMonth(),showDay); }
function showDay(date, stages) { $("#day-detail").innerHTML=stages.length?`<h3>${date}</h3>${stages.map(({event,stage})=>`<article><b>${event.title}</b><span>${stage.label}</span><button class="edit-event" data-id="${event.id}">直す</button></article>`).join("")}`:`<h3>${date}</h3><p>よていはありません。</p>`; document.querySelectorAll(".edit-event").forEach(button=>button.onclick=()=>openForm(events.find(event=>event.id===button.dataset.id))); }
function refreshTimeline(){const kind=$("#range-kind").value; activeRange=rangeFor(kind,$("#range-start").value,$("#range-end").value); $("#range-start").value=iso(activeRange.start); $("#range-end").value=iso(activeRange.end); renderTimeline($("#timeline"),events,id=>imageUrl(id,library),activeRange);}
function openForm(event) { $("#event-form").reset(); $("#stages").innerHTML=""; $("#event-id").value=event?.id||""; $("#form-heading").textContent=event?"行事を直す":"行事を入れる"; $("#event-title").value=event?.title||""; $("#event-category").value=event?.category||"gyouji"; (event?.stages||[{date:iso(new Date()),label:"",imageId:""}]).forEach(addStage); $("#event-dialog").showModal(); }
function addStage(data={}) { const node=$("#stage-template").content.firstElementChild.cloneNode(true); node.querySelector(".stage-date").value=data.date||iso(new Date()); node.querySelector(".stage-label").value=data.label||""; node.querySelector(".stage-image").value=data.imageId||""; node.querySelector(".remove-stage").onclick=()=>node.remove(); node.querySelector(".choose-image").onclick=()=>openPalette(node); $("#stages").append(node); }
async function openPalette(stage) { selectedStage=stage; const uploaded=(await import("./storage.js")).getAllImages; const uploads=await uploaded(); const entries=[...library,...uploads.map(x=>({id:x.id,label:x.name,category:"upload"}))]; $("#image-palette").innerHTML=entries.map(item=>`<button type="button" data-id="${item.id}"><img alt="" src="${item.path||""}"><span>${item.label}</span></button>`).join(""); for(const item of uploads){const button=$("#image-palette").querySelector(`[data-id="${item.id}"]`);button.querySelector("img").src=URL.createObjectURL(item.blob)} document.querySelectorAll("#image-palette button").forEach(button=>button.onclick=()=>chooseImage(button.dataset.id)); $("#image-dialog").showModal(); }
function chooseImage(id){selectedStage.querySelector(".stage-image").value=id; const meta=library.find(x=>x.id===id); selectedStage.querySelector(".chosen-image").textContent=`選択中：${meta?.label||"アップロード画像"}`; $("#image-dialog").close();}
async function uploadImage(e){if(!e.target.files[0])return; chooseImage(await saveImage(e.target.files[0]));e.target.value="";}
function saveForm(e){e.preventDefault(); const id=$("#event-id").value||crypto.randomUUID(); const event={id,title:$("#event-title").value.trim(),category:$("#event-category").value,type:"stage",stages:[...document.querySelectorAll(".stage-form")].map(node=>({date:node.querySelector(".stage-date").value,label:node.querySelector(".stage-label").value.trim(),imageId:node.querySelector(".stage-image").value})).sort((a,b)=>a.date.localeCompare(b.date))}; if(event.stages.some(x=>!x.imageId)){alert("各段階の写真・絵をえらんでください。");return} const index=events.findIndex(x=>x.id===id); if(index<0)events.push(event);else events[index]=event; saveEvents(events); $("#event-dialog").close();refresh();}
init().catch(error=>{console.error(error);alert("読み込みに失敗しました。Webサーバーまたは GitHub Pages で開いてください。")});
