(function(){
 'use strict';
 const G=window.HakoNetGeometry,$=s=>document.querySelector(s);
 const dialog=document.createElement('dialog');dialog.id='netWorkshop';dialog.setAttribute('aria-label','はこの形と展開図');
 dialog.innerHTML=`<div class="net-shell"><header class="net-header"><h2>6まいの面から、はこを作ろう</h2><button id="netClose">ふくしゅうへ もどる</button></header><div class="net-body">
 <div class="net-dimensions"><label>よこ <input id="netWidth" type="range" min="1" max="8" value="6"><output id="netWidthValue">6 cm</output></label><label>高さ <input id="netHeight" type="range" min="1" max="8" value="4"><output id="netHeightValue">4 cm</output></label><label>おくゆき <input id="netDepth" type="range" min="1" max="8" value="3"><output id="netDepthValue">3 cm</output></label><label>はこの形 <select id="netPreset"><option value="custom">じぶんで決める</option value="cuboid" selected>長方形の面のはこ</option><option value="cube">サイコロのようなはこ</option><option value="flat">うすいはこ</option></select></label></div>
 <nav class="net-steps" aria-label="作るじゅんばん"><button data-net-mode="box">1 はこの形を見る</button><button data-net-mode="faces">2 6まいに分ける</button><button data-net-mode="net">3 面をつないで作る</button></nav><p id="netInstruction" class="net-instruction"></p>
 <div class="net-columns"><div><div class="net-artboard"><svg id="netBoard" viewBox="0 0 800 620" tabindex="0" role="img" aria-label="6まいの面を動かす作業台"></svg></div><div class="net-tools" id="netTools"><label>動かす面 <select id="netSelected"></select></label><button id="netRotate">面を90°回す</button><button id="netUndo">1つもどす</button><label>つなぐ相手 <select id="netAnchor"></select></label><label>相手の <select id="netSide"><option value="E">みぎの辺</option><option value="W">ひだりの辺</option><option value="N">うえの辺</option><option value="S">したの辺</option></select></label><button id="netAttach">この辺につなぐ</button></div></div>
 <aside><div class="net-preview"><h3 id="netPreviewTitle">折ったときの形</h3><svg id="netPreview" viewBox="0 0 480 350" role="img" aria-label="面を折って箱にする様子"></svg><label id="netFoldControl"><span>開く</span> <input id="netFold" type="range" min="0" max="100" value="0" aria-label="折りたたむ量"><span>折る</span></label></div><div class="net-actions"><button id="netAssemble" class="net-assemble">はこになるか たしかめる</button><button id="netExample">見本の展開図</button><button id="netSeparate">6まいを並べなおす</button></div><p id="netMessage" class="net-message" role="status"></p><p class="net-tip">面をつかんで動かそう。辺をぴったり合わせると、つながるよ。面を選んで、矢印キーでも動かせます。「この辺につなぐ」ボタンでも作れます。</p></aside></div></div></div>`;
 document.body.appendChild(dialog);
 let dims=[6,4,3],fs=[],mode='box',selected='front',history=[],progress=0,animation=0,drag=null,cam={x:-.55,y:.65},viewDrag=null;
 const board=$('#netBoard'),preview=$('#netPreview');
 function message(text,result=''){const el=$('#netMessage');el.textContent=text;el.dataset.result=result}
 function remember(){history.push(fs.map(f=>({...f})));if(history.length>40)history.shift();$('#netUndo').disabled=!history.length}
 function separated(){const max=Math.max(...dims);fs=G.faces(dims).map((f,i)=>({...f,x:(i%3)*(max+3),y:Math.floor(i/3)*(max+4)}));history=[];selected='front';stop();progress=0;$('#netFold').value=0;render();message('6まいを、辺どうしでつなげてみよう。')}
 function stop(){cancelAnimationFrame(animation);animation=0}
 function geometry(){const max=Math.max(...dims),loX=-dims[2]-3,loY=-dims[2]-3,spanX=3*(max+3)+dims[2]+3,spanY=Math.max(2*dims[1]+2*dims[2]+6,2*(max+4)+dims[2]+3);const unit=Math.min(26,760/spanX,560/spanY);return{unit,ox:20-loX*unit,oy:25-loY*unit}}
 function polygon3d(f,frame){return G.corners(f,frame).map(p=>{const c=Math.cos(cam.y),s=Math.sin(cam.y),cx=Math.cos(cam.x),sx=Math.sin(cam.x),x=p[0]*c+p[2]*s,z=-p[0]*s+p[2]*c;return[x,p[1]*cx-z*sx,p[1]*sx+z*cx]})}
 function draw3d(target,faces,amount){const folded=G.folded(faces,amount);const polys=faces.map((f,i)=>{const frame=folded.frames[i]||{o:[f.x-faces[0].x,f.y-faces[0].y,0],r:[1,0,0],d:[0,1,0],n:[0,0,1]};return{f,points:polygon3d(f,frame)}});const pts=polys.flatMap(p=>p.points),minX=Math.min(...pts.map(p=>p[0])),maxX=Math.max(...pts.map(p=>p[0])),minY=Math.min(...pts.map(p=>p[1])),maxY=Math.max(...pts.map(p=>p[1]));const box=target===board?[800,620]:[480,350],scale=Math.min((box[0]-65)/Math.max(1,maxX-minX),(box[1]-65)/Math.max(1,maxY-minY));
  const project=p=>[box[0]/2+(p[0]-(maxX+minX)/2)*scale,box[1]/2+(p[1]-(maxY+minY)/2)*scale];polys.sort((a,b)=>a.points.reduce((s,p)=>s+p[2],0)-b.points.reduce((s,p)=>s+p[2],0));target.innerHTML=polys.map(({f,points})=>{const ps=points.map(project),center=[0,1].map(k=>ps.reduce((s,p)=>s+p[k],0)/4);return `<g><polygon points="${ps.map(p=>p.join(',')).join(' ')}" fill="${f.color}" fill-opacity=".72" stroke="#f3fbff" stroke-width="3"/><text x="${center[0]}" y="${center[1]}" text-anchor="middle" dominant-baseline="middle" fill="#071526" font-size="18" font-weight="900">${f.name}</text></g>`}).join('');
 }
 function galleryHtml(d){const faces=G.faces(d),max=Math.max(...d),unit=Math.min(42,190/max);return `<svg viewBox="0 0 800 600" role="img" aria-label="向かい合う面を同じ色にした6まいの長方形"><text x="400" y="44" text-anchor="middle" fill="#f7fbff" font-size="27" font-weight="900">同じ色・同じ形が 2まいずつ</text>${[faces[0],faces[2],faces[4],faces[1],faces[3],faces[5]].map((f,i)=>{const x=140+(i%3)*260,y=170+Math.floor(i/3)*250,w=f.w*unit,h=f.h*unit;return `<g data-flat-face="${f.id}"><rect x="${x-w/2}" y="${y-h/2}" width="${w}" height="${h}" fill="${f.color}" stroke="#f2fbff" stroke-width="3"/><text x="${x}" y="${y+h/2+34}" text-anchor="middle" fill="#f7fbff" font-size="22" font-weight="800">${f.name}の面</text></g>`}).join('')}<text x="400" y="585" text-anchor="middle" fill="#c8d9ef" font-size="20">6まいとも、この はこの面の大きさです。</text></svg>`}
 function refreshSelectors(){const options=fs.map(f=>`<option value="${f.id}">${f.name}（${G.size(f).join(' × ')} cm）</option>`).join('');$('#netSelected').innerHTML=options;$('#netSelected').value=selected;const anchor=$('#netAnchor').value;$('#netAnchor').innerHTML=fs.filter(f=>f.id!==selected).map(f=>`<option value="${f.id}">${f.name}</option>`).join('');$('#netAnchor').value=fs.some(f=>f.id===anchor&&f.id!==selected)?anchor:fs.find(f=>f.id!==selected).id}
 function drawBoard(){if(mode==='box'){draw3d(board,G.example(dims),1);return}if(mode==='faces'){board.innerHTML=galleryHtml(dims).replace(/^<svg[^>]*>|<\/svg>$/g,'');return}
  const{unit,ox,oy}=geometry();board.innerHTML=`<defs><pattern id="netGrid" width="${unit}" height="${unit}" x="${ox%unit}" y="${oy%unit}" patternUnits="userSpaceOnUse"><path d="M ${unit} 0 H 0 V ${unit}" fill="none" stroke="#345174" stroke-width="1"/></pattern></defs><rect width="800" height="620" fill="url(#netGrid)"/>`+fs.map(f=>{const[w,h]=G.size(f),x=ox+f.x*unit,y=oy+f.y*unit;return `<g data-face="${f.id}" role="button" tabindex="0" aria-label="${f.name}の面、${w}センチメートルかける${h}センチメートル"><rect x="${x}" y="${y}" width="${w*unit}" height="${h*unit}" fill="${f.color}" fill-opacity=".9" stroke="${f.id===selected?'#fff':'#172b42'}" stroke-width="${f.id===selected?5:2}"/><text x="${x+w*unit/2}" y="${y+h*unit/2}" fill="#0b2336" text-anchor="middle" dominant-baseline="middle" font-size="${Math.min(18,unit*.9)}" font-weight="900" pointer-events="none">${f.name}</text></g>`}).join('');
 }
 function render(){refreshSelectors();drawBoard();draw3d(preview,mode==='net'?fs:G.example(dims),mode==='net'?progress:1);$('#netTools').classList.toggle('net-hidden',mode!=='net');$('#netFoldControl').classList.toggle('net-hidden',mode!=='net');$('#netAssemble').classList.toggle('net-hidden',mode!=='net');$('#netPreviewTitle').textContent=mode==='net'?'折ったときの形':'この6まいからできる はこ';$('#netUndo').disabled=!history.length;document.querySelectorAll('[data-net-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.netMode===mode)));$('#netInstruction').textContent=({box:'よこ・高さ・おくゆきを変えて、いろいろな はこを見よう。図をつかむと回せます。',faces:'向かい合う面は同じ色。同じ大きさと形の面を、2まいずつ見比べよう。',net:'6まいを動かして、長さが同じ辺どうしをぴったりつなごう。'})[mode]}
 function changed(){stop();progress=0;$('#netFold').value=0;render();message('つなぎ方を変えたね。「はこになるか たしかめる」を押そう。')}
 function point(e,svg=board){return new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse())}
 board.addEventListener('pointerdown',e=>{if(mode==='box'){viewDrag={p:[e.clientX,e.clientY],target:board};board.setPointerCapture(e.pointerId);return}if(mode!=='net')return;const id=e.target.closest('[data-face]')?.dataset.face;if(!id)return;selected=id;const f=fs.find(f=>f.id===id);remember();stop();progress=0;$('#netFold').value=0;drag={id,p:point(e),x:f.x,y:f.y};board.setPointerCapture(e.pointerId);board.focus();refreshSelectors();drawBoard()});
 board.addEventListener('pointermove',e=>{if(viewDrag?.target===board){rotateView(e);return}if(!drag)return;const p=point(e),{unit,ox,oy}=geometry(),f=fs.find(f=>f.id===drag.id),[w,h]=G.size(f);f.x=Math.max(Math.ceil(-ox/unit),Math.min(Math.floor((800-ox)/unit-w),Math.round(drag.x+(p.x-drag.p.x)/unit)));f.y=Math.max(Math.ceil(-oy/unit),Math.min(Math.floor((620-oy)/unit-h),Math.round(drag.y+(p.y-drag.p.y)/unit)));drawBoard();draw3d(preview,fs,0)});
 board.addEventListener('pointerup',()=>{viewDrag=null;if(!drag)return;drag=null;changed()});board.addEventListener('pointercancel',()=>{drag=null;viewDrag=null});
 board.addEventListener('keydown',e=>{if(mode!=='net')return;const id=e.target.closest('[data-face]')?.dataset.face;if(id)selected=id;const f=fs.find(f=>f.id===selected),offset={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(offset){e.preventDefault();remember();f.x+=offset[0];f.y+=offset[1];changed()}if(e.key.toLowerCase()==='r'){e.preventDefault();rotateSelected()}});
 function rotateView(e){cam.y+=(e.clientX-viewDrag.p[0])*.01;cam.x+=(e.clientY-viewDrag.p[1])*.01;viewDrag.p=[e.clientX,e.clientY];draw3d(preview,mode==='net'?fs:G.example(dims),mode==='net'?progress:1);if(mode==='box')draw3d(board,G.example(dims),1)}
 preview.addEventListener('pointerdown',e=>{viewDrag={p:[e.clientX,e.clientY],target:preview};preview.setPointerCapture(e.pointerId)});preview.addEventListener('pointermove',e=>{if(viewDrag?.target===preview)rotateView(e)});preview.addEventListener('pointerup',()=>viewDrag=null);preview.addEventListener('pointercancel',()=>viewDrag=null);
 function rotateSelected(){remember();fs.find(f=>f.id===selected).turn++;changed()}
 $('#netRotate').onclick=rotateSelected;$('#netUndo').onclick=()=>{stop();fs=history.pop()||fs;changed()};$('#netSelected').onchange=e=>{selected=e.target.value;render()};
 $('#netAttach').onclick=()=>{const a=fs.find(f=>f.id===$('#netAnchor').value),b=fs.find(f=>f.id===selected),dir=$('#netSide').value,[aw,ah]=G.size(a),[bw,bh]=G.size(b);if((dir==='E'||dir==='W')?ah!==bh:aw!==bw){message('辺の長さがちがうよ。動かす面を回すか、つなぐ相手の辺を変えてみよう。','ng');return}remember();b.x=dir==='E'?a.x+aw:dir==='W'?a.x-bw:a.x;b.y=dir==='S'?a.y+ah:dir==='N'?a.y-bh:a.y;changed()};
 $('#netFold').oninput=e=>{stop();progress=+e.target.value/100;draw3d(preview,fs,progress);const result=G.check(fs,dims);if(result.frames?.some(f=>!f))message('はなれた面があるよ。6まいをつないでから、折ってみよう。','ng');else if(progress===1)message(result.message,result.ok?'ok':'ng')};
 $('#netAssemble').onclick=()=>{stop();const result=G.check(fs,dims);message(result.message,result.ok?'ok':'ng');if(!result.frames||result.frames.some(f=>!f))return;const start=performance.now();progress=0;function tick(now){progress=Math.min(1,(now-start)/1800);$('#netFold').value=Math.round(progress*100);draw3d(preview,fs,progress);if(progress<1)animation=requestAnimationFrame(tick);else animation=0}animation=requestAnimationFrame(tick)};
 $('#netExample').onclick=()=>{stop();mode='net';remember();fs=G.example(dims);selected='front';progress=0;$('#netFold').value=0;render();message('見本を折ってたしかめよう。自分で面の場所を変えてもいいよ。')};$('#netSeparate').onclick=()=>{mode='net';separated()};
 document.querySelectorAll('[data-net-mode]').forEach(b=>b.onclick=()=>{stop();mode=b.dataset.netMode;render();message(mode==='net'?'面の場所を自分で決めて、はこを作ろう。':'同じ色の面を見比べてみよう。')});
 function resize(){dims=['#netWidth','#netHeight','#netDepth'].map(id=>+$(id).value);['Width','Height','Depth'].forEach((name,i)=>$('#net'+name+'Value').textContent=dims[i]+' cm');separated();render()}
 ['Width','Height','Depth'].forEach(name=>$('#net'+name).oninput=()=>{$('#netPreset').value='custom';const oldMode=mode;resize();mode=oldMode;render();message('はこの大きさを変えたので、6まいの面も変わりました。')});
 $('#netPreset').onchange=e=>{const d=({cuboid:[6,4,3],cube:[4,4,4],flat:[7,2,5]})[e.target.value];if(!d)return;['Width','Height','Depth'].forEach((name,i)=>$('#net'+name).value=d[i]);const oldMode=mode;resize();mode=oldMode;render()};
 $('#netClose').onclick=()=>dialog.close();dialog.addEventListener('close',stop);dialog.addEventListener('keydown',e=>e.stopPropagation());
 function open(){if(!fs.length)separated();mode='box';render();message('まず、はこの形と6まいの面を見てみよう。');dialog.showModal()}
 function loadCubeNet(points){
  if(!points.length||points.length>7)return;stop();dims=[1,1,1];
  ['Width','Height','Depth'].forEach(name=>{$('#net'+name).value=1;$('#net'+name+'Value').textContent='1 cm'});
  $('#netPreset').value='cube';const defaults=G.faces(dims);fs=points.map((p,i)=>({...defaults[i%6],id:i<6?defaults[i].id:'extra',name:i<6?defaults[i].name:'7まいめ',x:p[0],y:p[1]}));
  mode='net';selected='front';history=[];progress=0;$('#netFold').value=0;render();
  message('土堂の問題のつなぎ方です。折って、予想をたしかめよう。');dialog.showModal();
 }
 function loadFaceSet(source){
  stop();const unit=Math.min(...source.flatMap(f=>[f.w,f.h]));
  const lengths=[...new Set(source.flatMap(f=>[f.w/unit,f.h/unit]))].sort((a,b)=>b-a);
  dims=lengths.length===1?[1,1,1]:lengths;
  ['Width','Height','Depth'].forEach((name,i)=>{$('#net'+name).step='any';$('#net'+name).value=dims[i];$('#net'+name+'Value').textContent=Number(dims[i].toFixed(2))+' cm'});
  $('#netPreset').value=lengths.length===1?'cube':'custom';
  const used=new Set();fs=G.example(dims).map(f=>{const i=source.findIndex((s,j)=>!used.has(j)&&((s.w/unit===f.w&&s.h/unit===f.h)||(s.h/unit===f.w&&s.w/unit===f.h)));used.add(i);return{...f,color:source[i].color}});
  mode='net';selected='front';history=[];progress=0;$('#netFold').value=0;render();message('同じ長さの辺どうしを合わせたよ。折って はこになるか見よう。');dialog.showModal();
 }
 window.HakoNets={open,loadCubeNet,loadFaceSet,galleryHtml,getState:()=>({dims:[...dims],faces:fs.map(f=>({...f})),mode,progress}),check:()=>G.check(fs,dims)};
 document.querySelectorAll('[data-open-nets]').forEach(b=>b.onclick=open);
})();
