'use strict';
(() => {
 const D=window.PHONICS, $=id=>document.getElementById(id), app=$('app');
 const state={mode:'letters',letter:'a',sound:'m',vowel:'a',consonant:'m',blendVowel:'a',gap:100,fontExample:'a'};
 let audio=null,audioURL=null,toastTimer=null,animation=null,recording=null,recordTimer=null,saving=false;
 const records=new Map(),targets=new Map();
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const wordImage=key=>'assets/words/'+(key==='hats'?'hat':key)+'.webp';
 const mouthImage=key=>'assets/mouths/'+key+'.webp?v=20261004-outward';
 const stopSounds=new Set(['b','d','g','p','t','k','kw','ks','ch','j','ts']);
 D.alphabet.forEach((l,i)=>targets.set('letter:'+l,{group:'文字の名前',label:l.toUpperCase()+' '+l+' の名前（'+D.names[i]+'）',hint:'文字の名前を1回。児童がまねする間を空けて、もう1回。'}));
 D.sounds.forEach(s=>targets.set('sound:'+s.id,{group:'英語の音',label:s.letters+' の音 /'+s.ipa+'/',hint:s.action+'。'+(stopSounds.has(s.id)?'止めて開く音は短く実演。余分な「ウ」を付けません。':'余分な母音を付けず、音だけを示します。')}));
 const uniqueWords=new Set(D.sounds.flatMap(s=>s.examples.map(w=>w.key)));
 uniqueWords.forEach(w=>targets.set('word:'+w,{group:'英語の単語',label:D.words[w][1]+'（'+D.words[w][0]+'）',hint:'単語全体を自然な英語で2回。児童がまねする間を空けます。'}));
 D.vowels.forEach(v=>targets.set('jp:'+v.id,{group:'日本語の母音',label:v.id+'「'+v.kana+'」',hint:'日本語の自然な「'+v.kana+'」を2回。英語の母音とは分けて録音。'}));
 Object.keys(D.syllables).forEach(c=>D.vowels.forEach((v,i)=>['far','near','joined'].forEach(stage=>targets.set(`blend:${c}:${v.id}:${stage}`,{group:'日本語の音をつなぐ',label:`${c} ＋ ${v.id}「${D.syllables[c][i]}」：${{far:'離して',near:'近づけて',joined:'つないで'}[stage]}`,hint:stage==='joined'?`閉じる・狭める動きから、そのまま日本語の母音へ。「${D.syllables[c][i]}」を自然に実演。`:stage==='far'?'初めの音、約1秒の間、日本語の母音。破裂音は短く。':'初めの音、約0.3秒の間、日本語の母音。破裂音は短く。'}))));
 const dbReady=new Promise((resolve,reject)=>{
  if(!window.indexedDB){reject(new Error('このブラウザーでは録音を保存できません。'));return;}
  const req=indexedDB.open('phonics-lab-voice',1);
  req.onupgradeneeded=()=>req.result.createObjectStore('recordings',{keyPath:'key'});
  req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(new Error('別のタブを閉じて、もう一度開いてください。'));
 });
 async function readRecords(){const db=await dbReady;return new Promise((resolve,reject)=>{const req=db.transaction('recordings').objectStore('recordings').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
 async function saveRecords(items){const db=await dbReady;await new Promise((resolve,reject)=>{const tx=db.transaction('recordings','readwrite');items.forEach(item=>tx.objectStore('recordings').put(item));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('保存できませんでした。'));});items.forEach(item=>records.set(item.key,item));}
 function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3300);}
 function stopAudio(){if(audio){audio.pause();audio.src='';audio=null;}if(audioURL){URL.revokeObjectURL(audioURL);audioURL=null;}document.querySelectorAll('.audio-button.playing').forEach(b=>b.classList.remove('playing'));}
 async function play(key,button){stopAudio();const rec=records.get(key);if(!rec){toast('先生の声を入れると、ここから聞けます。');return;}audioURL=URL.createObjectURL(rec.blob);const current=new Audio(audioURL);audio=current;button?.classList.add('playing');current.onended=()=>{if(audio===current)stopAudio();};current.onerror=()=>{if(audio===current){stopAudio();toast('この音声を再生できません。別の形式で入れ直してください。');}};try{await current.play();}catch(e){stopAudio();toast('再生できませんでした。もう一度「聞く」を押してください。');}}
 function listen(key,label='音を聞く'){return `<button class="audio-button ${records.has(key)?'has-audio':''}" data-audio="${esc(key)}" aria-label="${esc(targets.get(key)?.label||label)}を聞く"><span aria-hidden="true">▶</span>${esc(label)}</button>`;}
 function voice(voiced){return `<div class="voice-status ${voiced?'':'off'}"><span class="wave" aria-hidden="true"><i></i><i></i><i></i></span>${voiced==='mixed'?'k は声なし、w はぶるぶる':'のど '+(voiced?'ぶるぶる':'ぶるぶるしない')}</div>`;}
 function mouth(key,alt){return `<img class="mouth-image" src="${mouthImage(key)}" alt="${esc(alt)}">`;}
 function legend(){return '<div class="diagram-legend"><span><i class="legend-dot"></i>舌</span><span><i class="legend-dot air"></i>息</span></div><p class="mouth-caption">口の動きを示す、かんたんな図</p>';}
 function arrows(index,length,type){return `<div class="page-arrows"><button class="secondary" data-prev="${type}" ${index===0?'disabled':''}>← ひとつ前</button><button class="primary" data-next="${type}" ${index===length-1?'disabled':''}>次へ →</button></div>`;}
 function wordCard(w){const label=esc(w.label.slice(0,w.start))+'<mark>'+esc(w.label.slice(w.start,w.start+w.length))+'</mark>'+esc(w.label.slice(w.start+w.length));return `<article class="word-card"><div class="word-pictures ${w.key==='hats'?'double':''}"><img src="${wordImage(w.key)}" alt="${esc(w.ja)}">${w.key==='hats'?`<img src="${wordImage(w.key)}" alt="">`:''}</div><h3 class="word-spelling" lang="en">${label}</h3><p class="word-meaning">${esc(w.ja)}</p>${listen('word:'+w.key,'単語を聞く')}</article>`;}
 function heading(n,title,note,count=''){return `<div class="page-heading"><div><p class="eyebrow">LESSON ${n}</p><h1>${title}</h1><p>${note}</p></div><span class="count">${count}</span></div>`;}
 function renderLetters(){const i=D.alphabet.indexOf(state.letter), l=state.letter;return heading(1,'形がちがっても、同じ文字','まずは、文字の名前と形を見つけよう。',`${i+1} / 26`)+`<div class="sound-strip" aria-label="アルファベットを選ぶ">${D.alphabet.map(v=>`<button data-letter="${v}" class="${v===l?'active':''}" aria-pressed="${v===l}">${v.toUpperCase()}</button>`).join('')}</div><section class="lesson-sheet"><div class="letter-main"><div class="letter-pair"><div class="glyph">${l.toUpperCase()}<span>大文字</span></div><div class="glyph">${l}<span>小文字</span></div></div><div class="letter-copy"><h2>この文字の名前は</h2><p class="letter-name">${D.names[i]}</p>${listen('letter:'+l,'名前を聞く')}<p class="lesson-note">ことばの中の音も、あとで聞いてみよう。</p><button class="compare-button" data-go-sound="${D.letterSounds[i]}">この文字の音を見る →</button></div></div><div class="font-story"><h2>書体がかわると、形もかわる</h2><p>本や画面に出てくる文字は、形が少しちがうことがあるよ。</p><div class="letter-compare"><span class="small">くらべる文字</span>${['a','g',l].filter((v,i,a)=>a.indexOf(v)===i).map(v=>`<button data-font-letter="${v}" class="${state.fontExample===v?'active':''}" aria-pressed="${state.fontExample===v}">${v}</button>`).join('')}</div><div class="font-samples"><div class="font-sample"><div class="sample-glyph">${state.fontExample}</div><p>すっきりした書体</p></div><div class="font-sample"><div class="sample-glyph">${state.fontExample}</div><p>本で見かける書体</p></div><div class="font-sample"><div class="sample-glyph">${state.fontExample}</div><p>手書きに近い書体</p></div></div><p class="font-message">どれも、同じ「${state.fontExample}」なんだね。</p><p class="small">書くときは、先生の手書きの形も見てみよう。</p></div></section>`+arrows(i,26,'letter');}
 function renderSounds(){const s=D.sounds.find(v=>v.id===state.sound),i=D.sounds.indexOf(s);let diagram;
 if(s.id==='kw'||s.id==='ks'||s.id==='ts'){const second={kw:'w',ks:'s',ts:'s'}[s.id];diagram=`<div class="mouth-pair"><div><img src="${mouthImage(s.mouth)}" alt="${esc(s.action)}の初めの動き"><span>はじめの動き</span></div><div><img src="${mouthImage(second)}" alt="続く${second}の動き"><span>続く動き</span></div></div>`;}
 else if(s.id==='ch'||s.id==='j'){diagram=`<div class="mouth-pair"><div><img src="${mouthImage('ch')}" alt="舌の前でふさぐ"><span>いったん ふさぐ</span></div><div><img src="${mouthImage('sh')}" alt="はなして息を出す"><span>はなす</span></div></div>`;}
 else diagram=mouth(s.mouth,s.action+'。'+s.hint);
 return heading(2,'文字と、口の音','先生の声をまねして、口の動きをためそう。',`${i+1} / ${D.sounds.length}`)+`<div class="sound-strip" aria-label="英語の音を選ぶ">${D.sounds.map(v=>`<button data-sound="${v.id}" class="${v.id===s.id?'active':''} ${v.letters.includes('・')?'dual':''}" aria-label="${esc(v.letters)} ${v.id==='dh'?'声を出す音':v.id==='th'?'息の音':v.examples[0].label+'の音'}" aria-pressed="${v.id===s.id}">${v.letters}${v.id==='dh'?'<small>声</small>':''}</button>`).join('')}</div><section class="lesson-sheet"><div class="sound-main"><div><div class="sound-intro"><div class="sound-letters ${s.letters.length>2?'long':''}">${s.letters}</div><div class="sound-info"><p class="mini-label">ことばの中の音<span class="teacher-ipa">/${s.ipa}/</span></p>${listen('sound:'+s.id)}</div></div><h2 class="action-text">${s.action}</h2><p class="hint-text">${s.hint}</p>${voice(s.voiced)}${D.pair[s.id]?`<br><button class="compare-button" data-sound="${D.pair[s.id]}">${D.sounds.find(v=>v.id===D.pair[s.id]).letters} の音と、くらべる →</button>`:''}</div><div class="mouth-block">${diagram}${legend()}</div></div><div class="word-section"><div class="word-section-head"><h2>同じ音を、ことばの中で見つけよう</h2><p>色のついたつづりに、注目。</p></div><div class="word-grid ${s.examples.length===4?'four':''}">${s.examples.map(wordCard).join('')}</div></div></section>`+arrows(i,D.sounds.length,'sound');}
 function renderVowels(){const v=D.vowels.find(v=>v.id===state.vowel);return heading(3,'今度は、日本語の音','ここからは、日本語の「あ・い・う・え・お」を使うよ。')+`<div class="vowel-tabs" aria-label="日本語の母音">${D.vowels.map(v=>`<button data-vowel="${v.id}" class="${v.id===state.vowel?'active':''}" aria-pressed="${v.id===state.vowel}">${v.kana}</button>`).join('')}</div><section class="lesson-sheet"><div class="vowel-main"><div><p class="vowel-glyph">${v.id}　<strong>${v.kana}</strong></p><h2 class="action-text">${v.action}</h2>${listen('jp:'+v.id,'日本語の音を聞く')}<br>${voice(true)}</div><div class="mouth-block">${mouth(v.mouth,v.action)}${legend()}</div></div><p class="lesson-note">同じ文字でも、英語の音と日本語の音はちがうんだね。</p></section><div class="page-arrows"><button class="secondary" data-mode="sounds">← 英語の音へ</button><button class="primary" data-mode="blend">音をつないでみよう →</button></div>`;}
 function syllable(){return D.syllables[state.consonant][D.vowels.findIndex(v=>v.id===state.blendVowel)];}
 function blendStage(){return state.gap>66?'far':state.gap>10?'near':'joined';}
 function renderBlend(){const v=D.vowels.find(v=>v.id===state.blendVowel), c=state.consonant;return heading(4,'ローマ字表の、ひみつ','はじめの動きと、母音をつないでみよう。')+`<section class="lesson-sheet"><div class="blend-layout"><div><div class="blend-controls"><div><label>はじめの動き（子音）</label><div class="choice-row">${Object.keys(D.syllables).map(k=>`<button data-consonant="${k}" class="${k===c?'active':''}" aria-pressed="${k===c}">${k}</button>`).join('')}</div></div><div><label>あとの音（母音）</label><div class="choice-row vowels">${D.vowels.map(v=>`<button data-blend-vowel="${v.id}" class="${v.id===state.blendVowel?'active':''}" aria-pressed="${v.id===state.blendVowel}">${v.id}</button>`).join('')}</div></div></div><div class="blend-stage" style="--gap:${state.gap}" aria-label="${c}と${v.id}の間隔"><span class="blend-letter">${c}</span><span class="blend-letter vowel">${v.id}</span></div><div id="blend-result" class="blend-result" aria-live="polite">${state.gap<=10?syllable():'　'}</div><p id="blend-state" class="blend-state"></p><label class="small" for="gap-range">文字を近づける</label><input id="gap-range" class="blend-range" type="range" min="0" max="100" value="${100-state.gap}" aria-label="文字を近づける"><div class="range-labels"><span>はなれている</span><span>つながる</span></div><div class="blend-buttons"><button id="blend-animate" class="primary">近づけて、つなぐ</button><button id="blend-listen" class="secondary">▶ この音を聞く</button><button id="blend-reset" class="secondary">はなす</button></div></div><aside class="blend-explain"><h2>口の動きも、つながる</h2><p>${c==='m'?'くちびるを閉じて、声を出す。':c==='k'?'舌の奥で、息を止める。':c==='n'?'舌先で口をふさいで、鼻へ息を出す。':'くちびるを閉じて、息を止める。'}</p><p>そこから、そのまま「${v.kana}」の口へ。</p><div class="blend-mouths"><figure><img src="${mouthImage(c)}" alt="${c}の初めの口の動き"><figcaption>はじめの動き</figcaption></figure><figure><img src="${mouthImage(v.mouth)}" alt="日本語の${v.kana}の口"><figcaption>「${v.kana}」の口へ</figcaption></figure></div><p class="teacher-setup-note">先生が実演した「離す・近づける・つなぐ」の声で、聞きくらべよう。</p></aside></div><table class="romaji-table"><caption class="hidden">子音と母音で作るローマ字表の一部</caption><thead><tr><th scope="col">＋</th>${D.vowels.map(v=>`<th scope="col">${v.id} ${v.kana}</th>`).join('')}</tr></thead><tbody>${Object.keys(D.syllables).map(k=>`<tr><th scope="row">${k}</th>${D.vowels.map((v,i)=>`<td><button data-cell="${k}:${v.id}" class="${k===c&&v.id===state.blendVowel?'active':''}" aria-label="${k+v.id}、${D.syllables[k][i]}">${k+v.id}<small>${D.syllables[k][i]}</small></button></td>`).join('')}</tr>`).join('')}</tbody></table><p class="table-caption">表の一部を見ているよ。行は、はじめの動き。列は、母音。</p></section><p class="lesson-note">「し・ち・つ」「ら行」「ん・っ・きゃ」の書き方も、続きで見つけよう。</p>`;}
 function updateBlend(){const stage=blendStage();document.querySelector('.blend-stage')?.style.setProperty('--gap',state.gap);if($('gap-range'))$('gap-range').value=100-state.gap;if($('blend-result'))$('blend-result').textContent=stage==='joined'?syllable():'　';if($('blend-state'))$('blend-state').textContent={far:'音を離して、聞いてみよう。',near:'音の間が、短くなる。',joined:'つながると、「'+syllable()+'」の音になる。'}[stage];if($('blend-listen'))$('blend-listen').textContent='▶ '+{far:'離した音',near:'近づけた音',joined:'つないだ音'}[stage]+'を聞く';}
 function cancelAnimation(){if(animation!==null){cancelAnimationFrame(animation);animation=null;}}
 function animateBlend(){cancelAnimation();stopAudio();const from=state.gap,start=performance.now(),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;function tick(now){const t=reduce?1:Math.min(1,(now-start)/1700);state.gap=Math.round(from*(1-t*t*(3-2*t)));updateBlend();if(t<1)animation=requestAnimationFrame(tick);else{animation=null;const key=`blend:${state.consonant}:${state.blendVowel}:joined`;if(records.has(key))play(key,$('blend-listen'));}}animation=requestAnimationFrame(tick);}
 function render(){cancelAnimation();stopAudio();document.querySelectorAll('.lesson-nav button').forEach(b=>{if(b.dataset.mode===state.mode)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});app.innerHTML=({letters:renderLetters,sounds:renderSounds,vowels:renderVowels,blend:renderBlend})[state.mode]();if(state.mode==='blend')updateBlend();try{localStorage.setItem('phonics-lab-state',JSON.stringify({mode:state.mode,letter:state.letter,sound:state.sound,vowel:state.vowel}));}catch{} }
 function changeMode(mode){if(!['letters','sounds','vowels','blend'].includes(mode))return;state.mode=mode;history.replaceState(null,'','#'+mode);render();}
 app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.audio){play(b.dataset.audio,b);return;}if(b.dataset.letter){state.letter=b.dataset.letter;state.fontExample=['a','g'].includes(state.letter)?state.letter:'a';render();}else if(b.dataset.sound){state.sound=b.dataset.sound;render();}else if(b.dataset.goSound){state.sound=b.dataset.goSound;changeMode('sounds');}else if(b.dataset.vowel){state.vowel=b.dataset.vowel;render();}else if(b.dataset.mode){changeMode(b.dataset.mode);}else if(b.dataset.fontLetter){state.fontExample=b.dataset.fontLetter;render();}else if(b.dataset.consonant){state.consonant=b.dataset.consonant;state.gap=100;render();}else if(b.dataset.blendVowel){state.blendVowel=b.dataset.blendVowel;state.gap=100;render();}else if(b.dataset.cell){[state.consonant,state.blendVowel]=b.dataset.cell.split(':');state.gap=100;render();animateBlend();}else if(b.dataset.prev||b.dataset.next){const type=b.dataset.prev||b.dataset.next, delta=b.dataset.prev?-1:1;if(type==='letter'){state.letter=D.alphabet[D.alphabet.indexOf(state.letter)+delta];state.fontExample=['a','g'].includes(state.letter)?state.letter:'a';}else state.sound=D.sounds[D.sounds.findIndex(v=>v.id===state.sound)+delta].id;render();}else if(b.id==='blend-animate'){animateBlend();}else if(b.id==='blend-reset'){cancelAnimation();stopAudio();state.gap=100;updateBlend();}else if(b.id==='blend-listen'){play(`blend:${state.consonant}:${state.blendVowel}:${blendStage()}`,b);}});
 app.addEventListener('input',e=>{if(e.target.id==='gap-range'){cancelAnimation();stopAudio();state.gap=100-Number(e.target.value);updateBlend();}});
 document.querySelectorAll('.lesson-nav button').forEach(b=>b.addEventListener('click',()=>changeMode(b.dataset.mode)));
 document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();changeMode('letters');});
 window.addEventListener('hashchange',()=>changeMode(location.hash.slice(1)));
 function currentTarget(){if(state.mode==='letters')return 'letter:'+state.letter;if(state.mode==='sounds')return 'sound:'+state.sound;if(state.mode==='vowels')return 'jp:'+state.vowel;return `blend:${state.consonant}:${state.blendVowel}:${blendStage()}`;}
 const select=$('record-target');let lastGroup='';let group=null;targets.forEach((t,key)=>{if(t.group!==lastGroup){group=document.createElement('optgroup');group.label=t.group;select.append(group);lastGroup=t.group;}const opt=document.createElement('option');opt.value=key;opt.textContent=t.label;group.append(opt);});
 function updateRecorder(){const key=select.value,t=targets.get(key);$('record-state').textContent=records.has(key)?'保存した声があります。録音し直すと、この声を置き換えます。':'まだ声が入っていません。';$('record-state').classList.remove('recording');$('record-hint').textContent=t?.hint||'';$('record-play').disabled=!records.has(key);$('record-toggle').textContent='● 録音する';$('record-toggle').disabled=saving;select.disabled=saving;$('record-file').disabled=saving;}
 $('teacher-open').addEventListener('click',()=>{cancelAnimation();stopAudio();select.value=currentTarget();updateRecorder();$('teacher-dialog').showModal();});
 $('about-open').addEventListener('click',()=>$('about-dialog').showModal());
 document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
 $('teacher-dialog').addEventListener('close',()=>{if(recording){recording.cancelled=true;recording.recorder.stop();recording.stream.getTracks().forEach(t=>t.stop());}stopAudio();});
 $('teacher-dialog').addEventListener('cancel',()=>{if(saving)return;});
 select.addEventListener('change',()=>{stopAudio();updateRecorder();});
 async function startRecording(){if(recording){$('record-toggle').disabled=true;$('record-toggle').textContent='保存中…';recording.recorder.stop();recording.stream.getTracks().forEach(t=>t.stop());return;}if(saving)return;stopAudio();if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$('record-state').textContent='この画面では直接録音できません。録音済みの音声ファイルを入れるか、HTTPSまたはlocalhostで開いてください。';return;}
  saving=true;$('record-toggle').disabled=true;select.disabled=true;$('record-state').textContent='マイクを準備しています…';
  try{await dbReady;const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(!$('teacher-dialog').open){stream.getTracks().forEach(t=>t.stop());saving=false;updateRecorder();return;}const mime=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));const recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);const job={stream,recorder,key:select.value,chunks:[],cancelled:false};recording=job;saving=false;recorder.ondataavailable=e=>{if(e.data.size)job.chunks.push(e.data);};recorder.onerror=()=>{job.cancelled=true;stream.getTracks().forEach(t=>t.stop());clearInterval(recordTimer);recording=null;saving=false;updateRecorder();$('record-state').textContent='録音できませんでした。もう一度ためしてください。';};recorder.onstop=async()=>{clearInterval(recordTimer);stream.getTracks().forEach(t=>t.stop());recording=null;saving=true;try{if(!job.cancelled){const blob=new Blob(job.chunks,{type:recorder.mimeType||job.chunks[0]?.type||'audio/webm'});if(blob.size===0)throw new Error('音声を録音できませんでした。');await saveRecords([{key:job.key,blob,updated:new Date().toISOString()}]);toast('先生の声を保存しました。');render();}}catch(e){toast(e.message||'録音を保存できませんでした。');}finally{saving=false;updateRecorder();}};recorder.start();$('record-toggle').disabled=false;$('record-toggle').textContent='■ 止めて保存';select.disabled=true;$('record-play').disabled=true;$('record-file').disabled=true;$('record-state').classList.add('recording');const started=Date.now();recordTimer=setInterval(()=>{const secs=Math.floor((Date.now()-started)/1000);$('record-state').textContent=`録音中　${secs}秒`;if(secs>=120&&recording){$('record-toggle').click();}},250);
  }catch(e){saving=false;updateRecorder();$('record-state').textContent=e.name==='NotAllowedError'?'マイクの使用が許可されていません。許可するか、音声ファイルを入れてください。':(e.message||'マイクを使用できませんでした。');}finally{if(!recording)$('record-file').disabled=false;}
 }
 $('record-toggle').addEventListener('click',startRecording);
 $('record-play').addEventListener('click',()=>play(select.value,$('record-play')));
 $('record-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file||recording||saving)return;try{if(!file.type.startsWith('audio/')&&!/\.(mp3|wav|m4a|ogg|webm)$/i.test(file.name))throw new Error('音声ファイルを選んでください。');if(file.size>25*1024*1024)throw new Error('25MB以下の音声を選んでください。');const mime=file.type||({'mp3':'audio/mpeg','wav':'audio/wav','m4a':'audio/mp4','ogg':'audio/ogg','webm':'audio/webm'}[file.name.split('.').pop().toLowerCase()]);await saveRecords([{key:select.value,blob:new Blob([await file.arrayBuffer()],{type:mime}),updated:new Date().toISOString()}]);updateRecorder();render();toast('音声を保存しました。');}catch(err){toast(err.message||'音声を保存できませんでした。');}});
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function toBase64(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});}
 $('backup-export').addEventListener('click',async()=>{if(recording||saving){toast('録音を止めてから、保存してください。');return;}if(!records.size){toast('まだ録音がありません。');return;}try{const entries=await Promise.all([...records.values()].map(async r=>({key:r.key,type:r.blob.type,updated:r.updated,data:await toBase64(r.blob)})));download(new Blob([JSON.stringify({format:'phonics-lab-voice',version:1,created:new Date().toISOString(),entries})],{type:'application/json'}),'おとラボ_先生の声_'+new Date().toISOString().slice(0,10)+'.json');toast('録音のバックアップを保存しました。');}catch{toast('バックアップを作れませんでした。');}});
 $('backup-import').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file||recording||saving)return;try{if(file.size>100*1024*1024)throw new Error('100MB以下のバックアップを選んでください。');const pack=JSON.parse(await file.text());if(pack.format!=='phonics-lab-voice'||pack.version!==1||!Array.isArray(pack.entries)||pack.entries.length>targets.size)throw new Error('おとラボのバックアップを選んでください。');const seen=new Set();const items=pack.entries.map(r=>{if(!targets.has(r.key)||seen.has(r.key)||typeof r.data!=='string'||!r.type?.startsWith('audio/')||r.data.length>35*1024*1024||!/^[A-Za-z0-9+/]*={0,2}$/.test(r.data))throw new Error('バックアップの内容を読み込めません。');seen.add(r.key);const bytes=Uint8Array.from(atob(r.data),c=>c.charCodeAt(0));if(!bytes.length)throw new Error('空の音声が含まれています。');return {key:r.key,blob:new Blob([bytes],{type:r.type}),updated:new Date().toISOString()};});await saveRecords(items);updateRecorder();render();toast(items.length+'件の声を読み込みました。');}catch(err){toast(err.message||'バックアップを読み込めませんでした。');}});
 $('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('この画面では全画面にできません。');}});
 window.addEventListener('pagehide',()=>{cancelAnimation();stopAudio();if(recording){recording.cancelled=true;recording.recorder.stop();recording.stream.getTracks().forEach(t=>t.stop());}});
 try{const saved=JSON.parse(localStorage.getItem('phonics-lab-state'));if(saved&&D.alphabet.includes(saved.letter))state.letter=saved.letter;if(saved&&D.sounds.some(v=>v.id===saved.sound))state.sound=saved.sound;if(saved&&D.vowels.some(v=>v.id===saved.vowel))state.vowel=saved.vowel;}catch{}
 const mode=location.hash.slice(1);if(['letters','sounds','vowels','blend'].includes(mode))state.mode=mode;
 render();
 readRecords().then(items=>{items.forEach(r=>{if(targets.has(r.key)&&r.blob instanceof Blob)records.set(r.key,r);});render();}).catch(()=>{ /* The lesson remains usable without persistent audio. */ });
})();
